Repository wzarek/Reasn, pull requests merged in 2024-06, with the labels that each got.

#45 [RSN-26] Change regexes to match more correct formats
  Database/init-constraints.sql
  Database/init-db.sql
Labels: scope: database, type: fix, status: ready for review

#44 [RSN-53] Add pre-commit hook to run fmt and lint
  Client/reasn-client/.husky/common.sh
  Client/reasn-client/.husky/pre-commit
  Client/reasn-client/apps/native/.eslintrc.js
  Client/reasn-client/apps/native/package.json
  Client/reasn-client/apps/web/.eslintrc.json
  Client/reasn-client/apps/web/app/layout.tsx
  Client/reasn-client/apps/web/package.json
  Client/reasn-client/apps/web/postcss.config.js
  Client/reasn-client/apps/web/tailwind.config.js
  Client/reasn-client/jest.config.ts
  Client/reasn-client/package.json
  Client/reasn-client/packages/common/__tests__/services/apiServices.test.ts
  Client/reasn-client/packages/common/enums/serviceEnums.ts
  Client/reasn-client/packages/common/errors/ApiAuthorizationError.ts
  Client/reasn-client/packages/common/errors/ApiConnectionError.ts
  Client/reasn-client/packages/common/interfaces/AuthData.ts
  Client/reasn-client/packages/common/package.json
  Client/reasn-client/packages/common/services/apiServices.ts
  Client/reasn-client/packages/common/services/authorizationServices.ts
  Client/reasn-client/packages/ui/postcss.config.js
  Client/reasn-client/packages/ui/tailwind.config.js
  Client/reasn-client/yarn.lock
  Server/ReasnAPI/.editorconfig
  Server/ReasnAPI/Directory.Build.props
  Server/ReasnAPI/ReasnAPI/Models/DTOs/AddressDto.cs
  Server/ReasnAPI/ReasnAPI/Models/DTOs/CommentDto.cs
  Server/ReasnAPI/ReasnAPI/Models/DTOs/EventDto.cs
  Server/ReasnAPI/ReasnAPI/Models/DTOs/ImageDto.cs
  Server/ReasnAPI/ReasnAPI/Models/DTOs/ParameterDto.cs
  Server/ReasnAPI/ReasnAPI/Models/DTOs/ParticipantDto.cs
  Server/ReasnAPI/ReasnAPI/Models/DTOs/TagDto.cs
  Server/ReasnAPI/ReasnAPI/Models/DTOs/UserDto.cs
  Server/ReasnAPI/ReasnAPI/Models/Database/ReasnContext.cs
  Server/ReasnAPI/ReasnAPI/Models/Enums/EventStatus.cs
Labels: scope: ci/cd, type: feature, status: ready for review

#32 [RSN-31] - Create validators according to constraints
  Server/ReasnAPI/ReasnAPI.Tests/ReasnAPI.Tests.csproj
  Server/ReasnAPI/ReasnAPI.Tests/UnitTest1.cs
  Server/ReasnAPI/ReasnAPI.Tests/UnitTests/Exceptions/ServiceExceptionHandlerTests.cs
  Server/ReasnAPI/ReasnAPI.Tests/UnitTests/Exceptions/ValidationExceptionHandlerTests.cs
  Server/ReasnAPI/ReasnAPI.Tests/UnitTests/Services/Authentication/AuthServiceTests.cs
  Server/ReasnAPI/ReasnAPI.Tests/UnitTests/Services/Authentication/TokenServiceTests.cs
  Server/ReasnAPI/ReasnAPI.Tests/UnitTests/Validators/AddressValidatorTests.cs
  Server/ReasnAPI/ReasnAPI.Tests/UnitTests/Validators/Authentication/LoginRequestValidatorTests.cs
  Server/ReasnAPI/ReasnAPI.Tests/UnitTests/Validators/Authentication/RegisterRequestValidatorTests.cs
  Server/ReasnAPI/ReasnAPI.Tests/UnitTests/Validators/CommentValidatorTests.cs
  Server/ReasnAPI/ReasnAPI.Tests/UnitTests/Validators/EventValidatorTests.cs
  Server/ReasnAPI/ReasnAPI.Tests/UnitTests/Validators/InterestValidatorTests.cs
  Server/ReasnAPI/ReasnAPI.Tests/UnitTests/Validators/ParameterValidatorTests.cs
  Server/ReasnAPI/ReasnAPI.Tests/UnitTests/Validators/TagValidatorTests.cs
  Server/ReasnAPI/ReasnAPI.Tests/UnitTests/Validators/UserValidatorTests.cs
  Server/ReasnAPI/ReasnAPI/Common/IAssemblyMarker.cs
  Server/ReasnAPI/ReasnAPI/Controllers/.gitkeep
  Server/ReasnAPI/ReasnAPI/Controllers/AuthController.cs
  Server/ReasnAPI/ReasnAPI/Controllers/UsersController.cs
  Server/ReasnAPI/ReasnAPI/Exceptions/ServiceExceptionHandler.cs
  Server/ReasnAPI/ReasnAPI/Exceptions/ValidationExceptionHandler.cs
  Server/ReasnAPI/ReasnAPI/Mappers/AddressMapper.cs
  Server/ReasnAPI/ReasnAPI/Mappers/InterestMapper.cs
  Server/ReasnAPI/ReasnAPI/Mappers/UserInterestMapper.cs
  Server/ReasnAPI/ReasnAPI/Mappers/UserMapper.cs
  Server/ReasnAPI/ReasnAPI/Models/Authentication/LoginRequest.cs
  Server/ReasnAPI/ReasnAPI/Models/Authentication/RegisterRequest.cs
  Server/ReasnAPI/ReasnAPI/Models/Authentication/TokenPayload.cs
  Server/ReasnAPI/ReasnAPI/Models/Database/ReasnContext.cs
  Server/ReasnAPI/ReasnAPI/Models/Enums/UserRole.cs
  Server/ReasnAPI/ReasnAPI/Program.cs
  Server/ReasnAPI/ReasnAPI/ReasnAPI.csproj
  Server/ReasnAPI/ReasnAPI/Services/.gitkeep
  Server/ReasnAPI/ReasnAPI/Services/Authentication/AuthService.cs
  Server/ReasnAPI/ReasnAPI/Services/Authentication/TokenService.cs
  Server/ReasnAPI/ReasnAPI/Services/Exceptions/BadRequestException.cs
  Server/ReasnAPI/ReasnAPI/Services/Exceptions/NotFoundException.cs
  Server/ReasnAPI/ReasnAPI/Services/Exceptions/VerificationException.cs
  Server/ReasnAPI/ReasnAPI/Validators/.gitkeep
  Server/ReasnAPI/ReasnAPI/Validators/AddressValidator.cs
  Server/ReasnAPI/ReasnAPI/Validators/Authentication/LoginRequestValidator.cs
  Server/ReasnAPI/ReasnAPI/Validators/Authentication/RegisterRequestValidator.cs
  Server/ReasnAPI/ReasnAPI/Validators/CommentValidator.cs
  Server/ReasnAPI/ReasnAPI/Validators/EventValidator.cs
  Server/ReasnAPI/ReasnAPI/Validators/InterestValidator.cs
  Server/ReasnAPI/ReasnAPI/Validators/ParameterValidator.cs
  Server/ReasnAPI/ReasnAPI/Validators/TagValidator.cs
  Server/ReasnAPI/ReasnAPI/Validators/UserValidator.cs
  Server/ReasnAPI/ReasnAPI/appsettings.json
  compose.override.yml
Labels: scope: backend, type: feature, status: ready for review

#46 [RSN-43] - Implemented card component with variants (to refactor)
  Client/reasn-client/.prettierrc
  Client/reasn-client/package.json
  Client/reasn-client/packages/ui/src/components/Card.tsx
  Client/reasn-client/packages/ui/src/index.tsx
  Client/reasn-client/yarn.lock
Labels: scope: frontend, type: feature, status: ready for review

#29 [RSN-41] - create hero component
  Client/reasn-client/apps/web/app/page.tsx
  Client/reasn-client/apps/web/styles/index.module.css
  Client/reasn-client/packages/ui/src/components/Card.tsx
  Client/reasn-client/packages/ui/src/components/main/HeroSection.tsx
  Client/reasn-client/packages/ui/src/icons/Fire.tsx
  Client/reasn-client/packages/ui/src/icons/IconProps.ts
  Client/reasn-client/packages/ui/src/index.tsx
Labels: scope: frontend, type: feature

#43 [RSN-40] Add user authentication
  Server/ReasnAPI/ReasnAPI.Tests/UnitTests/Exceptions/ServiceExceptionHandlerTests.cs
  Server/ReasnAPI/ReasnAPI.Tests/UnitTests/Services/Authentication/AuthServiceTests.cs
  Server/ReasnAPI/ReasnAPI/Controllers/AuthController.cs
  Server/ReasnAPI/ReasnAPI/Controllers/UsersController.cs
  Server/ReasnAPI/ReasnAPI/Middlewares/GlobalRoutePrefixMiddleware.cs
  Server/ReasnAPI/ReasnAPI/Models/Authentication/TokenPayload.cs
  Server/ReasnAPI/ReasnAPI/Models/Database/ReasnContext.cs
  Server/ReasnAPI/ReasnAPI/Models/Enums/UserRole.cs
  Server/ReasnAPI/ReasnAPI/Program.cs
  Server/ReasnAPI/ReasnAPI/Services/Authentication/AuthService.cs
  Server/ReasnAPI/ReasnAPI/Validators/AddressValidator.cs
  Server/ReasnAPI/ReasnAPI/Validators/Authentication/RegisterRequestValidator.cs
Labels: scope: backend, type: feature, status: ready for review

#49 [RSN-63] - Implemented quick filters section
  Client/reasn-client/apps/web/app/page.tsx
  Client/reasn-client/package.json
  Client/reasn-client/packages/ui/src/components/Card.tsx
  Client/reasn-client/packages/ui/src/components/main/QuickFilters.tsx
  Client/reasn-client/packages/ui/src/index.tsx
  Client/reasn-client/yarn.lock
  Server/ReasnAPI/ReasnAPI/Models/Enums/UserRole.cs
Labels: scope: frontend, type: feature, status: ready for review

#40 [RSN-34] - Create navbar and footer
  Client/reasn-client/apps/web/app/page.tsx
  Client/reasn-client/apps/web/tailwind.config.js
  Client/reasn-client/packages/ui/src/button.tsx
  Client/reasn-client/packages/ui/src/components/shared/Card.tsx
  Client/reasn-client/packages/ui/src/components/shared/Footer.tsx
  Client/reasn-client/packages/ui/src/components/shared/Navbar.tsx
  Client/reasn-client/packages/ui/src/components/shared/index.tsx
  Client/reasn-client/packages/ui/src/components/web/index.tsx
  Client/reasn-client/packages/ui/src/components/web/main/HeroSection.tsx
  Client/reasn-client/packages/ui/src/components/web/main/QuickFilters.tsx
  Client/reasn-client/packages/ui/src/icons/index.tsx
  Client/reasn-client/packages/ui/src/index.tsx
Labels: scope: frontend, type: feature, status: ready for review

#50 [RSN-64] - CTA section (ui only)
  Client/reasn-client/apps/web/app/page.tsx
  Client/reasn-client/packages/ui/src/components/web/index.tsx
  Client/reasn-client/packages/ui/src/components/web/main/CTASection.tsx
Labels: scope: frontend, type: feature, status: ready for review

#19 [RSN-38] - Create services (address, comment, objecttype, participant, role, user*)
  Database/init-db.sql
  Database/init-dev-data.sql
  Server/ReasnAPI/ReasnAPI.Tests/ReasnAPI.Tests.csproj
  Server/ReasnAPI/ReasnAPI.Tests/Services/AddressServiceTests.cs
  Server/ReasnAPI/ReasnAPI.Tests/Services/CommentServiceTests.cs
  Server/ReasnAPI/ReasnAPI.Tests/Services/FakeDbSet.cs
  Server/ReasnAPI/ReasnAPI.Tests/Services/ParticipantServiceTests.cs
  Server/ReasnAPI/ReasnAPI.Tests/Services/UserServiceTests.cs
  Server/ReasnAPI/ReasnAPI.Tests/UnitTest1.cs
  Server/ReasnAPI/ReasnAPI/Exceptions/BadRequestException.cs
  Server/ReasnAPI/ReasnAPI/Exceptions/NotFoundException.cs
  Server/ReasnAPI/ReasnAPI/Mappers/AddressMapper.cs
  Server/ReasnAPI/ReasnAPI/Mappers/CommentMapper.cs
  Server/ReasnAPI/ReasnAPI/Mappers/InterestMapper.cs
  Server/ReasnAPI/ReasnAPI/Mappers/ParticipantMapper.cs
  Server/ReasnAPI/ReasnAPI/Mappers/UserInterestMapper.cs
  Server/ReasnAPI/ReasnAPI/Mappers/UserMapper.cs
  Server/ReasnAPI/ReasnAPI/Models/DTOs/UserDto.cs
  Server/ReasnAPI/ReasnAPI/Models/Database/ReasnContext.cs
  Server/ReasnAPI/ReasnAPI/Models/Enums/EventStatus.cs
  Server/ReasnAPI/ReasnAPI/Models/Enums/ObjectType.cs
  Server/ReasnAPI/ReasnAPI/Models/Enums/ParticipantStatus.cs
  Server/ReasnAPI/ReasnAPI/Models/Enums/UserRole.cs
  Server/ReasnAPI/ReasnAPI/Program.cs
  Server/ReasnAPI/ReasnAPI/Services/AddressService.cs
  Server/ReasnAPI/ReasnAPI/Services/CommentService.cs
  Server/ReasnAPI/ReasnAPI/Services/ObjectTypeService.cs
  Server/ReasnAPI/ReasnAPI/Services/ParticipantService.cs
  Server/ReasnAPI/ReasnAPI/Services/RoleService.cs
  Server/ReasnAPI/ReasnAPI/Services/StatusService.cs
  Server/ReasnAPI/ReasnAPI/Services/UserService.cs
Labels: scope: backend, type: feature, status: ready for review

#15 [RSN-9] - Implemented DTO models on frontend
  .github/workflows/unit-tests.yml
  Client/reasn-client/package.json
  Client/reasn-client/packages/common/__tests__/models/AddressDto.test.ts
  Client/reasn-client/packages/common/__tests__/models/CommentDto.test.ts
  Client/reasn-client/packages/common/__tests__/models/EventDto.test.ts
  Client/reasn-client/packages/common/__tests__/models/ImageDto.test.ts
  Client/reasn-client/packages/common/__tests__/models/InterestDto.test.ts
  Client/reasn-client/packages/common/__tests__/models/ParameterDto.test.ts
  Client/reasn-client/packages/common/__tests__/models/ParticipantDto.test.ts
  Client/reasn-client/packages/common/__tests__/models/TagDto.test.ts
  Client/reasn-client/packages/common/__tests__/models/UserDto.test.ts
  Client/reasn-client/packages/common/__tests__/models/UserInterestDto.test.ts
  Client/reasn-client/packages/common/enums/modelsEnums.ts
  Client/reasn-client/packages/common/enums/serviceEnums.ts
  Client/reasn-client/packages/common/errors/ModelMappingError.ts
  Client/reasn-client/packages/common/models/AddressDto.ts
  Client/reasn-client/packages/common/models/CommentDto.ts
  Client/reasn-client/packages/common/models/EventDto.ts
  Client/reasn-client/packages/common/models/ImageDto.ts
  Client/reasn-client/packages/common/models/InterestDto.ts
  Client/reasn-client/packages/common/models/ParameterDto.ts
  Client/reasn-client/packages/common/models/ParticipantDto.ts
  Client/reasn-client/packages/common/models/TagDto.ts
  Client/reasn-client/packages/common/models/UserDto.ts
  Client/reasn-client/packages/common/models/UserInterestDto.ts
  Client/reasn-client/packages/common/services/authorizationServices.ts
  Client/reasn-client/yarn.lock
Labels: scope: frontend, scope: mobile, type: feature, status: require changes

#51 [RSN-65] - Implemented base routing and base register page
  Client/reasn-client/apps/web/app/layout.tsx
  Client/reasn-client/apps/web/app/login/layout.tsx
  Client/reasn-client/apps/web/app/login/page.tsx
  Client/reasn-client/apps/web/app/page.tsx
  Client/reasn-client/apps/web/app/register/layout.tsx
  Client/reasn-client/apps/web/app/register/organizer/page.tsx
  Client/reasn-client/apps/web/app/register/page.tsx
  Client/reasn-client/apps/web/app/register/user/page.tsx
  Client/reasn-client/apps/web/styles/index.module.css
  Client/reasn-client/apps/web/tsconfig.json
  Client/reasn-client/packages/ui/src/components/shared/Navbar.tsx
  Client/reasn-client/packages/ui/src/components/shared/form/Button.tsx
  Client/reasn-client/packages/ui/src/components/shared/form/Input.tsx
  Client/reasn-client/packages/ui/src/components/shared/form/index.tsx
  Client/reasn-client/packages/ui/src/components/web/main/QuickFilters.tsx
Labels: scope: frontend, type: feature, status: ready for review

#53 [RSN-67] Add more event statuses and fix some errors
  Database/init-db.sql
  Database/init-dev-data.sql
  Database/init-users.sh
  Server/ReasnAPI/ReasnAPI/Models/Authentication/LoginRequest.cs
  Server/ReasnAPI/ReasnAPI/Models/Authentication/RegisterRequest.cs
  Server/ReasnAPI/ReasnAPI/Models/Database/ReasnContext.cs
  Server/ReasnAPI/ReasnAPI/Models/Enums/EventStatus.cs
  Server/ReasnAPI/ReasnAPI/Models/Enums/ObjectType.cs
  Server/ReasnAPI/ReasnAPI/Models/Enums/ParticipantStatus.cs
  Server/ReasnAPI/ReasnAPI/ReasnAPI.csproj
  Server/ReasnAPI/ReasnAPI/Services/Authentication/AuthService.cs
Labels: scope: backend, scope: database, type: feature, type: fix, status: ready for review

#54 [RSN-56] Add regex validation for dtos
  Client/reasn-client/packages/common/__tests__/models/EventDto.test.ts
  Client/reasn-client/packages/common/__tests__/models/UserDto.test.ts
  Client/reasn-client/packages/common/models/AddressDto.ts
  Client/reasn-client/packages/common/models/CommentDto.ts
  Client/reasn-client/packages/common/models/EventDto.ts
  Client/reasn-client/packages/common/models/InterestDto.ts
  Client/reasn-client/packages/common/models/ParameterDto.ts
  Client/reasn-client/packages/common/models/TagDto.ts
  Client/reasn-client/packages/common/models/UserDto.ts
Labels: scope: frontend, scope: mobile, type: feature, status: ready for review

#55 [RSN-68] - Implemented base login page
  Client/reasn-client/apps/web/app/login/page.tsx
Labels: scope: frontend, type: feature, status: ready for review

#57 [RSN-70] - Implemented base user info page (for me and for user/username)
  Client/reasn-client/apps/web/app/me/layout.tsx
  Client/reasn-client/apps/web/app/me/page.tsx
  Client/reasn-client/apps/web/app/user/[username]/layout.tsx
  Client/reasn-client/apps/web/app/user/[username]/page.tsx
  Client/reasn-client/packages/ui/src/components/shared/Interest.tsx
  Client/reasn-client/packages/ui/src/components/shared/form/Button.tsx
  Client/reasn-client/packages/ui/src/components/shared/form/Input.tsx
  Client/reasn-client/packages/ui/src/components/shared/index.tsx
  Client/reasn-client/packages/ui/src/components/web/index.tsx
  Client/reasn-client/packages/ui/src/components/web/main/QuickFilters.tsx
  Client/reasn-client/packages/ui/src/components/web/user/SharedUserPage.tsx
Labels: scope: frontend, type: feature, status: ready for review

#67 [RSN-71] - Implemented event browse page
  Client/reasn-client/apps/web/app/events/[slug]/edit/page.tsx
  Client/reasn-client/apps/web/app/events/layout.tsx
  Client/reasn-client/apps/web/app/events/new/page.tsx
  Client/reasn-client/apps/web/app/events/page.tsx
  Client/reasn-client/apps/web/tailwind.config.js
  Client/reasn-client/packages/common/src/helpers/uiHelpers.ts
  Client/reasn-client/packages/ui/src/components/shared/Card.tsx
  Client/reasn-client/packages/ui/src/components/shared/Comment.tsx
  Client/reasn-client/packages/ui/src/components/shared/form/Dropdown.tsx
  Client/reasn-client/packages/ui/src/components/web/main/QuickFilters.tsx
  Client/reasn-client/packages/ui/tailwind.config.js
Labels: scope: frontend, type: feature

#58 [RSN-60] - Implement required methods in MeController and UserController
  Server/ReasnAPI/ReasnAPI.Tests/Services/ParticipantServiceTests.cs
  Server/ReasnAPI/ReasnAPI.Tests/Services/UserServiceTests.cs
  Server/ReasnAPI/ReasnAPI/Controllers/MeController.cs
  Server/ReasnAPI/ReasnAPI/Controllers/UsersController.cs
  Server/ReasnAPI/ReasnAPI/Mappers/ParticipantMapper.cs
  Server/ReasnAPI/ReasnAPI/Mappers/UserInterestMapper.cs
  Server/ReasnAPI/ReasnAPI/Mappers/UserMapper.cs
  Server/ReasnAPI/ReasnAPI/Models/DTOs/ParticipantDto.cs
  Server/ReasnAPI/ReasnAPI/Models/DTOs/UserDto.cs
  Server/ReasnAPI/ReasnAPI/Program.cs
  Server/ReasnAPI/ReasnAPI/Services/EventService.cs
  Server/ReasnAPI/ReasnAPI/Services/ImageService.cs
  Server/ReasnAPI/ReasnAPI/Services/ParameterService.cs
  Server/ReasnAPI/ReasnAPI/Services/ParticipantService.cs
  Server/ReasnAPI/ReasnAPI/Services/UserService.cs
Labels: scope: backend, type: feature, status: ready for review

#70 [RSN-84] - Implemented UI for adding a comment
  Client/reasn-client/apps/web/app/events/[slug]/page.tsx
  Client/reasn-client/packages/ui/src/components/shared/Comment.tsx
  Client/reasn-client/packages/ui/src/components/shared/form/Dropdown.tsx
  Client/reasn-client/packages/ui/src/components/shared/index.tsx
Labels: scope: frontend, type: feature, status: ready for review

#59 [RSN-59] - Created EventsController
  Server/ReasnAPI/ReasnAPI.Tests/Services/EventServicesTest.cs
  Server/ReasnAPI/ReasnAPI.Tests/UnitTests/Validators/EventValidatorTests.cs
  Server/ReasnAPI/ReasnAPI/Controllers/EventsController.cs
  Server/ReasnAPI/ReasnAPI/Controllers/MeController.cs
  Server/ReasnAPI/ReasnAPI/Controllers/UsersController.cs
  Server/ReasnAPI/ReasnAPI/Mappers/CommentMapper.cs
  Server/ReasnAPI/ReasnAPI/Mappers/EventMapper.cs
  Server/ReasnAPI/ReasnAPI/Mappers/ParticipantMapper.cs
  Server/ReasnAPI/ReasnAPI/Models/API/CommentRequest.cs
  Server/ReasnAPI/ReasnAPI/Models/API/EventCreateRequest.cs
  Server/ReasnAPI/ReasnAPI/Models/API/EventResponse.cs
  Server/ReasnAPI/ReasnAPI/Models/API/EventUpdateRequest.cs
  Server/ReasnAPI/ReasnAPI/Models/API/Organizer.cs
  Server/ReasnAPI/ReasnAPI/Models/API/Participants.cs
  Server/ReasnAPI/ReasnAPI/Models/API/ParticipantsResponse.cs
  Server/ReasnAPI/ReasnAPI/Models/DTOs/EventDto.cs
  Server/ReasnAPI/ReasnAPI/Services/EventService.cs
  Server/ReasnAPI/ReasnAPI/Services/ImageService.cs
  Server/ReasnAPI/ReasnAPI/Services/ParameterService.cs
  Server/ReasnAPI/ReasnAPI/Services/TagService.cs
  Server/ReasnAPI/ReasnAPI/Services/UserService.cs
  Server/ReasnAPI/ReasnAPI/Validators/EventValidator.cs
Labels: scope: backend, status: ready for review

#72 [RSN-85] Fix redirecting after successfully form submition
  Client/reasn-client/apps/web/app/login/action.ts
  Client/reasn-client/apps/web/app/register/action.ts
Labels: scope: frontend, type: fix, status: ready for review

#75 [RSN-86] Make frontend schemas compliant with backend requests/responses
  Client/reasn-client/apps/web/services/event.ts
  Client/reasn-client/apps/web/services/user.ts
  Client/reasn-client/packages/common/__tests__/schemas/CommentDto.test.ts
  Client/reasn-client/packages/common/__tests__/schemas/EventDto.test.ts
  Client/reasn-client/packages/common/__tests__/schemas/ImageDto.test.ts
  Client/reasn-client/packages/common/__tests__/schemas/InterestDto.test.ts
  Client/reasn-client/packages/common/__tests__/schemas/ParameterDto.test.ts
  Client/reasn-client/packages/common/__tests__/schemas/ParticipantDto.test.ts
  Client/reasn-client/packages/common/__tests__/schemas/TagDto.test.ts
  Client/reasn-client/packages/common/__tests__/schemas/UserDto.test.ts
  Client/reasn-client/packages/common/__tests__/schemas/UserInterestDto.test.ts
  Client/reasn-client/packages/common/src/schemas/CommentDto.ts
  Client/reasn-client/packages/common/src/schemas/CommentRequest.ts
  Client/reasn-client/packages/common/src/schemas/EventDto.ts
  Client/reasn-client/packages/common/src/schemas/EventResponse.ts
  Client/reasn-client/packages/common/src/schemas/ImageDto.ts
  Client/reasn-client/packages/common/src/schemas/InterestDto.ts
  Client/reasn-client/packages/common/src/schemas/ParameterDto.ts
  Client/reasn-client/packages/common/src/schemas/ParticipantDto.ts
  Client/reasn-client/packages/common/src/schemas/TagDto.ts
  Client/reasn-client/packages/common/src/schemas/UserInterestDto.ts
Labels: scope: frontend, type: cleanup/refactor, status: ready for review

#74 [RSN-83] - Implemented UI of user edit page
  Client/reasn-client/apps/web/app/me/edit/page.tsx
  Client/reasn-client/apps/web/app/user/[username]/edit/page.tsx
  Client/reasn-client/apps/web/middleware.ts
  Client/reasn-client/packages/ui/src/components/shared/form/Dropdown.tsx
  Client/reasn-client/packages/ui/src/components/web/index.tsx
  Client/reasn-client/packages/ui/src/components/web/main/QuickFilters.tsx
  Client/reasn-client/packages/ui/src/components/web/user/SharedEditUserPage.tsx
  Client/reasn-client/packages/ui/src/components/web/user/SharedUserPage.tsx
Labels: scope: frontend, type: feature, status: ready for review

#77 [RSN-75] - Implemented swiping for suggestions
  Client/reasn-client/apps/web/app/events/suggestions/page.tsx
  Client/reasn-client/apps/web/middleware.ts
  Client/reasn-client/apps/web/tailwind.config.js
  Client/reasn-client/packages/ui/src/components/shared/Card.tsx
  Client/reasn-client/packages/ui/src/components/shared/Comment.tsx
  Client/reasn-client/packages/ui/src/icons/Add.tsx
  Client/reasn-client/packages/ui/src/icons/Dismiss.tsx
  Client/reasn-client/packages/ui/src/icons/Question.tsx
  Client/reasn-client/packages/ui/src/icons/index.tsx
Labels: scope: frontend, type: feature, status: ready for review

#79 [RSN-19] - Create Controllers
  Server/ReasnAPI/ReasnAPI.Tests/Services/CommentServiceTests.cs
  Server/ReasnAPI/ReasnAPI.Tests/Services/EventServicesTest.cs
  Server/ReasnAPI/ReasnAPI.Tests/Services/ParticipantServiceTests.cs
  Server/ReasnAPI/ReasnAPI.Tests/Services/UserServiceTests.cs
  Server/ReasnAPI/ReasnAPI.Tests/UnitTests/Exceptions/ServiceExceptionHandlerTests.cs
  Server/ReasnAPI/ReasnAPI.Tests/UnitTests/Services/Authentication/AuthServiceTests.cs
  Server/ReasnAPI/ReasnAPI.Tests/UnitTests/Validators/EventValidatorTests.cs
  Server/ReasnAPI/ReasnAPI/Common/IAssemblyMarker.cs
  Server/ReasnAPI/ReasnAPI/Controllers/EventsController.cs
  Server/ReasnAPI/ReasnAPI/Controllers/MeController.cs
  Server/ReasnAPI/ReasnAPI/Controllers/UsersController.cs
  Server/ReasnAPI/ReasnAPI/Exceptions/ServiceExceptionHandler.cs
  Server/ReasnAPI/ReasnAPI/Mappers/CommentMapper.cs
  Server/ReasnAPI/ReasnAPI/Mappers/EventMapper.cs
  Server/ReasnAPI/ReasnAPI/Mappers/ParticipantMapper.cs
  Server/ReasnAPI/ReasnAPI/Mappers/UserInterestMapper.cs
  Server/ReasnAPI/ReasnAPI/Mappers/UserMapper.cs
  Server/ReasnAPI/ReasnAPI/Models/API/CommentRequest.cs
  Server/ReasnAPI/ReasnAPI/Models/API/EventCreateRequest.cs
  Server/ReasnAPI/ReasnAPI/Models/API/EventResponse.cs
  Server/ReasnAPI/ReasnAPI/Models/API/EventUpdateRequest.cs
  Server/ReasnAPI/ReasnAPI/Models/API/Organizer.cs
  Server/ReasnAPI/ReasnAPI/Models/API/Participants.cs
  Server/ReasnAPI/ReasnAPI/Models/API/ParticipantsResponse.cs
  Server/ReasnAPI/ReasnAPI/Models/DTOs/CommentDto.cs
  Server/ReasnAPI/ReasnAPI/Models/DTOs/EventDto.cs
  Server/ReasnAPI/ReasnAPI/Models/DTOs/ParticipantDto.cs
  Server/ReasnAPI/ReasnAPI/Models/DTOs/UserDto.cs
  Server/ReasnAPI/ReasnAPI/Program.cs
  Server/ReasnAPI/ReasnAPI/Services/CommentService.cs
  Server/ReasnAPI/ReasnAPI/Services/EventService.cs
  Server/ReasnAPI/ReasnAPI/Services/ImageService.cs
  Server/ReasnAPI/ReasnAPI/Services/ParameterService.cs
  Server/ReasnAPI/ReasnAPI/Services/ParticipantService.cs
  Server/ReasnAPI/ReasnAPI/Services/TagService.cs
  Server/ReasnAPI/ReasnAPI/Services/UserService.cs
  Server/ReasnAPI/ReasnAPI/Validators/EventValidator.cs
  Server/ReasnAPI/ReasnAPI/appsettings.json
Labels: scope: backend, type: feature, status: ready for review
